### ISSUE TITLE
latest release incomplete?

### ISSUE THREAD

**Issue by m-rnd** [nesyou01/LazyStaggeredGrid#5]
the changelog of release 1.1 says it fixes the scroll bug, but the affected changes do not seem to be included in the release. I'm importing `com.github.nesyou01:LazyStaggeredGrid:1.1`

**Comment by nesyou01** [comment]
Try the new release 1.2.0 🙌

**Comment by nesyou01** [comment]
Try the new release 1.2.0 🙌
